version: '3'

services:
  app_todos:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017
    restart: always
  mongo:
    image: mongo:latest
    ports:
      - 27019:27017
    restart: always